### ISSUE TITLE
Turn this repo into a Github Template instead of a standard repo

### ISSUE THREAD

**Issue by ATechAdventurer** [openrndr/openrndr-template#1]
It would be cool if you changed the repo type to a template so you don't have to fork the project, instead you could seed a new repo based on this one. https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

**Comment by edwinRNDR** [comment]
@ATechAdventurer great tip! I was completely unaware of the template repo feature.
