### ISSUE TITLE
"Unable to create primary window" issue

### ISSUE THREAD

**Issue by Sofianba** [openrndr/openrndr-template#17]
I get this error when I try to run the template : 

> Caused by:  java.lang.IllegalStateException: primary window could not be created.

My procedure was : 

- cloning the repository via version control.
- running "run" in the gradle tasks tab.

I tried this :
1. deleting the clone.
2. resetting IntelliJ IDEA to default settings. 
3. going through the same steps again.

**Comment by edwinRNDR** [comment]
Which platform and hardware are you using? `primary window could not be created` usually indicates that no OpenGL context could be created.

**Comment by hamoid** [comment]
Sometimes integrated graphics support up to 4.5 or 4.6. Are there new drivers available?

**Comment by Sofianba** [comment]
with the latest drivers installed now I can only run up to GL 3.1.

 In any case here's a GPU report with all info :
[gpu_caps_viewer_report.txt](https://github.com/openrndr/openrndr-template/files/6199847/gpu_caps_viewer_report.txt)

**Comment by hamoid** [comment]
According to https://guide.openrndr.org/#/01_Before_you_start/C02ShouldIUseOPENRNDR GL 3.3 unfortunately is the minimum.
