### ISSUE TITLE
Build constantly cancelled

### ISSUE THREAD

**Issue by somecho** [openrndr/openrndr-template#32]
Hello RNDR team! I'm back to tinkering with OpenRNDR again after a long gap. Starting a new project from VCS using this git repo, I got this error:  `Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve org.openrndr.extra:orx-git-archiver-gradle:0.4.1.`

I removed `orx-git-archiver` from the plugins and orxFeatures and the template builds as normal again. 

My setup:
- OS: Windows 20
- IntelliJ IDEA 2021.1.3 
- JDK 15

**Comment by hamoid** [comment]
Hi Sam-Tsao! :) It's a known issue. Discussed at https://openrndr.discourse.group/t/gradle-problem-after-git-clone/427/3
I think a fix is coming soon, but good that you found a workaround!

**Comment by edwinRNDR** [comment]
Seems like this problem only pops up with older JDKs? Think I will disable the plugin for the time being (since it is not really in use)
