### ISSUE TITLE
Version tags might better be named

### ISSUE THREAD

**Issue by hoijui** [openrndr/openrndr-template#5]
Hello! :-)
When I use this template (including the git history) as a starting point for my project,
it means that I have version tags in my history already, which I probably don't want.
A solution that I have also seen in the Java/JVM world, is to name the version tags, like so:
`openrndr-template-v0.3.4`, instead of just `v0.3.4`.

As it is now, I can locally delete the tags, but they get re-fetched every time I fetch from the template remote, which I might want to do, to merge in your latest version.

**Comment by edwinRNDR** [comment]
hi @hoijui, I never considered this but it is a fair point. There is currently nothing tied to the tags and they are assigned by hand at this point. Do you think we should rename the existing tags or is this for future versions only?

**Comment by hoijui** [comment]
ahh great! .. that nothing is tied to them!
I would say, they should be renamed in the whole history. If some people rely on them, they should already have them, and if you delete them, their local ones will not be deleted.
additionally, if you just add the name in front of the current tag names, it would be very easy to have a script do the opposite. you could even supply such a script, so people who rely on the tags as they are now, can even use future tags in this format, even if you use the name-added format from now on.

**Comment by hoijui** [comment]
wrote two simple BASH scripts for this.
Note that you have to remove the echos for something to actually happen.

_git-tag-version-nameify_:

```bash
#!/usr/bin/env bash
# Converts git version tags like this:
# * "v0.3.10"     -> "openrndr-v0.3.10"
# * "v0.3.25-rc1" -> "openrndr-v0.3.25-rc1"

project_name_tag="openrndr"

for tag_version in $(git tag \
	| grep '^v[0-9]\+\.[0-9]\+\.[0-9]\+\(-.*\)\?$')
do
	tag_name_version="$project_name_tag-$tag_version"
	echo git tag "$tag_name_version" "$tag_version"
	echo git tag -d "$tag_version"
done
```

_git-tag-version-unnameify_:

```bash
#!/usr/bin/env bash
# Converts git version tags like this:
# * "openrndr-v0.3.10"     -> "v0.3.10"
# * "openrndr-v0.3.25-rc1" -> "v0.3.25-rc1"

project_name_tag="openrndr"

for tag_name_version in $(git tag \
	| grep '^'$project_name_tag'-v[0-9]\+\.[0-9]\+\.[0-9]\+\(-.*\)\?$')
do
	tag_version=$(echo "$tag_name_version" \
		| sed -e 's|^'$project_name_tag'-||')
	echo git tag "$tag_version" "$tag_name_version"
	echo git tag -d "$tag_name_version"
done
```

**Comment by edwinRNDR** [comment]
Thanks! That only renames the tags locally though. I figured using  `git push --delete origin $tag_version` takes care of that

Tags are updated
