### ISSUE TITLE
Unable to build and run template due to missing native arm64 kinect library

### ISSUE THREAD

**Issue by octobeard** [openrndr/openrndr-template#52]
Following the basic steps to clone and run the openrndr-template project from the master branch seem to fail on a missing arm64 macos library. Building out of the box yields this error:

```
openrndr-template:main: Could not find org.openrndr.extra:orx-kinect-v1-natives-macos-arm64:0.4.4.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/org/openrndr/extra/orx-kinect-v1-natives-macos-arm64/0.4.4/orx-kinect-v1-natives-macos-arm64-0.4.4.pom
  - file:/Users//.m2/repository/org/openrndr/extra/orx-kinect-v1-natives-macos-arm64/0.4.4/orx-kinect-v1-natives-macos-arm64-0.4.4.pom
Required by:
    root project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

Navigating to the URL referenced above indeed yields a 404:
https://repo.maven.apache.org/maven2/org/openrndr/extra/orx-kinect-v1-natives-macos-arm64/0.4.4/orx-kinect-v1-natives-macos-arm64-0.4.4.pom

Replacing this library with a non-native macos url also fails. Only way I could get the template to run was to simply comment out the example from the TemplateProgram.kt, and more or less copy over the basic pink canvas example from the TemplateLiveProgram.kt while also commenting out "orx-kinect-v1" from the dependencies in the Gradle file.

Perhaps the kinect library and the template isn't compatible with Mac M1 chips?

**Comment by hamoid** [comment]
I'm very sorry about this. I accidentally pushed code that shouldn't be there (I had the wrong remote). Fixing it now.

**Comment by hamoid** [comment]
I'm happy that it only took a few hours for this issue to appear :-) 

Please re-open if not solved.

**Comment by octobeard** [comment]
It works! Thanks
